name: C++ Qt Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) 安装 Qt（APT 方式更稳定：不依赖 Qt 官方下载 / CDN / 速率限制）
      # 说明：只要能构建/运行 QtTest + QtSql(QSQLITE) 即可，不要求 CI 上与本地 Qt 版本完全一致。
      - name: Install build tools & Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential make gcovr \
            qt6-base-dev qt6-base-dev-tools \
            qt6-tools-dev qt6-tools-dev-tools \
            libqt6sql6-sqlite

      # 3) 构建并运行单元测试（QtTest）
      - name: Build & run QtTest
        working-directory: Lab4/project/tests
        run: |
          mkdir -p build
          cd build
          QMAKE_BIN="$(command -v qmake6 || command -v qmake)"
          echo "Using qmake: $QMAKE_BIN"
          "$QMAKE_BIN" "CONFIG+=coverage" ../LedgerAppTests.pro
          make -j2
          QT_QPA_PLATFORM=offscreen ./LedgerAppTests -maxwarnings 0

      # 4) 生成覆盖率报告（基于 gcov）
      - name: Coverage (gcovr)
        working-directory: Lab4/project/tests
        run: |
          cd build
          gcovr -r ../.. --object-directory . \
            --exclude "../../.qtcreator" --exclude "../build" \
            --print-summary --xml-pretty -o ../coverage.xml

      # 5) 上传覆盖率产物（便于下载查看，也方便截图）
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: Lab4/project/tests/coverage.xml
